//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nhom8_ecommerce.ContactDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLog
    {
        public int LogId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
    }
}
