//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenQuocDai_2118110097.ContactDB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int IdUser { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string Password { get; set; }
        
        public Nullable<bool> IsAdmin { get; set; }
    }
}
